// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlawwvugnnawtlssvtuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYXd3dnVnbm5hd3Rsc3N2dHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDA4NzIsImV4cCI6MjA2NTA3Njg3Mn0.NQq8s5SoJaTt4uOBs2Fuu5TssrurQRX5WTKEQo_GxXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);